#!/bin/bash

echo "=================================================="
echo "  🚀 酷狗乐库 - GitHub Pages部署指南"
echo "=================================================="
echo ""
echo "📝 请按以下步骤操作来获取互联网分享链接："
echo ""
echo "=================================================="
echo "  第一步：创建GitHub仓库"
echo "=================================================="
echo "1. 访问 https://github.com/new"
echo "2. 仓库名称建议：kugou-music-lib"
echo "3. 选择 Public（公开）"
echo "4. 不要勾选 Add a README file"
echo "5. 点击 Create repository"
echo ""
echo "=================================================="
echo "  第二步：推送代码"
echo "=================================================="
echo "创建仓库后，复制仓库地址（格式：https://github.com/你的用户名/仓库名.git）"
echo "然后在本目录运行："
echo ""
echo "  git remote add origin https://github.com/你的用户名/仓库名.git"
echo "  git push -u origin main"
echo ""
echo "=================================================="
echo "  第三步：启用GitHub Pages"
echo "=================================================="
echo "1. 进入仓库的 Settings 页面"
echo "2. 左侧点击 Pages"
echo "3. Source 选择：main 分支，/ (root) 目录"
echo "4. 点击 Save"
echo "5. 等待2-5分钟"
echo ""
echo "=================================================="
echo "  🎉 获取分享链接"
echo "=================================================="
echo "您的在线预览地址将是："
echo "  https://你的用户名.github.io/仓库名/yuelu_interactive.html"
echo ""
echo "例如："
echo "  https://example.github.io/kugou-music-lib/yuelu_interactive.html"
echo ""
echo "=================================================="
echo ""
echo "💡 替代方案（无需GitHub）："
echo "1. 使用 Netlify 部署：https://www.netlify.com"
echo "2. 使用 Vercel 部署：https://vercel.com"
echo "   直接拖放此文件夹即可一键部署！"
echo ""
