#!/bin/bash

echo "==============================================="
echo "  📤 GitHub 代码推送详细步骤"
echo "==============================================="
echo ""
echo "请按以下步骤操作："
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  第一步：获取GitHub仓库地址"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. 如果还没创建仓库，访问："
echo "   https://github.com/new"
echo ""
echo "2. 创建后复制仓库地址，格式是："
echo "   https://github.com/你的用户名/仓库名.git"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  第二步：执行以下命令"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "请将下面的 你的用户名 和 仓库名 替换为实际内容，"
echo "然后复制粘贴到终端运行："
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  git remote add origin https://github.com/你的用户名/仓库名.git"
echo ""
echo "  git push -u origin main"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 示例（假设用户名是zhangsan，仓库名是kugou-music-lib）："
echo ""
echo "  git remote add origin https://github.com/zhangsan/kugou-music-lib.git"
echo "  git push -u origin main"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📌 提示："
echo "- 如果提示需要登录，按提示输入GitHub账号密码"
echo "- 如果开启了2FA，需要用Personal Access Token"
echo "- 推送成功后，去GitHub仓库查看代码是否上传成功"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 快速测试：当前git状态"
echo ""
git status
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
